export enum Currency {
    EUR_SIGN = "€",
    EUR = "EUR",
    EUR_LONG = "Euro",
    USD_SIGN = "$",
    USD = "USD",
    USD_LONG = "United States Dollar",
    GBP_SIGN = "&#163;",
    GBP = "GBP",
    GBP_LONG = "Pound Sterling",
    CHF_SIGN = "CHF",
    CHF = "CHF",
    CHF_LONG = "Swiss Franc",
    CAD_SIGN = "CA$",
    CAD = "CAD",
    CAD_LONG = "Canadian Dollar",
}
