export enum DashboardMenu {
    DASHBOARD = 'DASHBOARD',
    BALANCE = 'BALANCE',
    SAVING_GOALS = 'SAVING_GOALS',
    ACCOUNTS = 'ACCOUNTS',
    TRANSACTIONS = 'TRANSACTIONS',
    PREFERENCES = 'PREFERENCES'
}
